// Package foundry is a gRPC client for foundry-service test-generation.
// Platform rule: service↔service = gRPC. The legacy REST fallback was
// removed in Foxtrot — callers must supply a gRPC channel via WithGRPC.
package foundry

import (
	"bytes"
	"context"
	"fmt"
	"time"

	"google.golang.org/grpc"
)

// Client talks to foundry-service over gRPC Dispatch(generate_tests).
type Client struct {
	dispatcher *grpcDispatcher
	timeout    time.Duration
}

// NewClient constructs a new foundry client. Must call WithGRPC before
// use — baseURL arg is ignored and retained for DI compatibility.
func NewClient(_ string, timeout time.Duration) *Client {
	if timeout <= 0 {
		timeout = 30 * time.Second
	}
	return &Client{timeout: timeout}
}

// WithGRPC attaches a foundry gRPC channel.
func (c *Client) WithGRPC(conn *grpc.ClientConn) *Client {
	if c == nil {
		return c
	}
	c.dispatcher = newGRPCDispatcher(conn)
	return c
}

// SetPreferGRPC is a no-op kept for API compatibility.
func (c *Client) SetPreferGRPC(_ bool) {}

// GenerateTestRequest carries acceptance criteria plus target language/framework.
type GenerateTestRequest struct {
	Criteria  []string `json:"criteria"`
	Framework string   `json:"framework"`
	Language  string   `json:"language"`
	Context   string   `json:"context,omitempty"`
}

// GenerateTestResponse captures the generated test source.
type GenerateTestResponse struct {
	Framework string `json:"framework"`
	Language  string `json:"language"`
	Code      string `json:"code"`
	Notes     string `json:"notes,omitempty"`
}

// FoundryClient is the public interface used by the use case. Having an
// interface lets tests supply a stub and lets non-Foundry deployments provide
// a template-based fallback generator.
type FoundryClient interface {
	GenerateTests(ctx context.Context, orgID string, req GenerateTestRequest) (*GenerateTestResponse, error)
}

// GenerateTests calls foundry-service gRPC Dispatch(generate_tests).
func (c *Client) GenerateTests(ctx context.Context, orgID string, req GenerateTestRequest) (*GenerateTestResponse, error) {
	if c == nil || c.dispatcher == nil {
		return nil, fmt.Errorf("foundry client not configured")
	}
	return c.dispatcher.generateTests(ctx, orgID, req)
}

// NoopClient is used when foundry-service is not configured. It synthesises a
// minimal scaffold so callers always get something runnable.
type NoopClient struct{}

// NewNoopClient returns a foundry client that returns templated scaffolds.
func NewNoopClient() *NoopClient { return &NoopClient{} }

// GenerateTests returns a deterministic scaffold for the requested framework.
func (c *NoopClient) GenerateTests(_ context.Context, _ string, req GenerateTestRequest) (*GenerateTestResponse, error) {
	return &GenerateTestResponse{
		Framework: req.Framework,
		Language:  req.Language,
		Code:      scaffoldTest(req),
		Notes:     "generated by noop-foundry fallback; replace with real AI call",
	}, nil
}

func scaffoldTest(req GenerateTestRequest) string {
	switch req.Framework {
	case "pytest":
		return pytestScaffold(req.Criteria)
	case "jest":
		return jestScaffold(req.Criteria)
	case "go":
		return goTestScaffold(req.Criteria)
	default:
		return pytestScaffold(req.Criteria)
	}
}

func pytestScaffold(criteria []string) string {
	buf := bytes.NewBufferString("# Auto-generated pytest scaffold\nimport pytest\n\n")
	for i, c := range criteria {
		fmt.Fprintf(buf, "def test_criterion_%d():\n    # %s\n    assert True\n\n", i+1, c)
	}
	return buf.String()
}

func jestScaffold(criteria []string) string {
	buf := bytes.NewBufferString("// Auto-generated jest scaffold\n\n")
	for i, c := range criteria {
		fmt.Fprintf(buf, "test('criterion %d', () => {\n  // %s\n  expect(true).toBe(true);\n});\n\n", i+1, c)
	}
	return buf.String()
}

func goTestScaffold(criteria []string) string {
	buf := bytes.NewBufferString("// Auto-generated go test scaffold\npackage main_test\n\nimport \"testing\"\n\n")
	for i, c := range criteria {
		fmt.Fprintf(buf, "func TestCriterion%d(t *testing.T) {\n    // %s\n    _ = t\n}\n\n", i+1, c)
	}
	return buf.String()
}
