// Package foundry wraps the foundry-service REST API for test code generation.
package foundry

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"
)

// Client is a thin HTTP client for foundry-service.
type Client struct {
	baseURL    string
	httpClient *http.Client
}

// NewClient constructs a new foundry-service client.
func NewClient(baseURL string, timeout time.Duration) *Client {
	if timeout <= 0 {
		timeout = 30 * time.Second
	}
	return &Client{
		baseURL: baseURL,
		httpClient: &http.Client{
			Timeout: timeout,
			Transport: &http.Transport{
				MaxIdleConns:        10,
				MaxIdleConnsPerHost: 10,
				IdleConnTimeout:     90 * time.Second,
			},
		},
	}
}

// GenerateTestRequest carries acceptance criteria plus target language/framework.
type GenerateTestRequest struct {
	Criteria  []string `json:"criteria"`
	Framework string   `json:"framework"`
	Language  string   `json:"language"`
	Context   string   `json:"context,omitempty"`
}

// GenerateTestResponse captures the generated test source.
type GenerateTestResponse struct {
	Framework string `json:"framework"`
	Language  string `json:"language"`
	Code      string `json:"code"`
	Notes     string `json:"notes,omitempty"`
}

// FoundryClient is the public interface used by the use case. Having an
// interface lets tests supply a stub and lets non-Foundry deployments provide
// a template-based fallback generator.
type FoundryClient interface {
	GenerateTests(ctx context.Context, orgID string, req GenerateTestRequest) (*GenerateTestResponse, error)
}

// GenerateTests calls foundry-service to generate test code.
func (c *Client) GenerateTests(ctx context.Context, orgID string, req GenerateTestRequest) (*GenerateTestResponse, error) {
	body, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("foundry: marshal: %w", err)
	}
	url := fmt.Sprintf("%s/api/v1/foundry/tests/generate", c.baseURL)
	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("foundry: new request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")
	if orgID != "" {
		httpReq.Header.Set("X-Organization-ID", orgID)
	}
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("foundry: request: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 300 {
		b, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("foundry: %s: %s", resp.Status, string(b))
	}
	var envelope struct {
		Success bool                 `json:"success"`
		Data    GenerateTestResponse `json:"data"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&envelope); err != nil {
		return nil, fmt.Errorf("foundry: decode: %w", err)
	}
	return &envelope.Data, nil
}

// NoopClient is used when foundry-service is not configured. It synthesises a
// minimal scaffold so callers always get something runnable.
type NoopClient struct{}

// NewNoopClient returns a foundry client that returns templated scaffolds.
func NewNoopClient() *NoopClient { return &NoopClient{} }

// GenerateTests returns a deterministic scaffold for the requested framework.
func (c *NoopClient) GenerateTests(_ context.Context, _ string, req GenerateTestRequest) (*GenerateTestResponse, error) {
	return &GenerateTestResponse{
		Framework: req.Framework,
		Language:  req.Language,
		Code:      scaffoldTest(req),
		Notes:     "generated by noop-foundry fallback; replace with real AI call",
	}, nil
}

func scaffoldTest(req GenerateTestRequest) string {
	switch req.Framework {
	case "pytest":
		return pytestScaffold(req.Criteria)
	case "jest":
		return jestScaffold(req.Criteria)
	case "go":
		return goTestScaffold(req.Criteria)
	default:
		return pytestScaffold(req.Criteria)
	}
}

func pytestScaffold(criteria []string) string {
	buf := bytes.NewBufferString("# Auto-generated pytest scaffold\nimport pytest\n\n")
	for i, c := range criteria {
		fmt.Fprintf(buf, "def test_criterion_%d():\n    # %s\n    assert True\n\n", i+1, c)
	}
	return buf.String()
}

func jestScaffold(criteria []string) string {
	buf := bytes.NewBufferString("// Auto-generated jest scaffold\n\n")
	for i, c := range criteria {
		fmt.Fprintf(buf, "test('criterion %d', () => {\n  // %s\n  expect(true).toBe(true);\n});\n\n", i+1, c)
	}
	return buf.String()
}

func goTestScaffold(criteria []string) string {
	buf := bytes.NewBufferString("// Auto-generated go test scaffold\npackage main_test\n\nimport \"testing\"\n\n")
	for i, c := range criteria {
		fmt.Fprintf(buf, "func TestCriterion%d(t *testing.T) {\n    // %s\n    _ = t\n}\n\n", i+1, c)
	}
	return buf.String()
}
