// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutputStream int32

const (
	OutputStream_STDOUT OutputStream = 0
	OutputStream_STDERR OutputStream = 1
)

// Enum value maps for OutputStream.
var (
	OutputStream_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
	}
	OutputStream_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
	}
)

func (x OutputStream) Enum() *OutputStream {
	p := new(OutputStream)
	*p = x
	return p
}

func (x OutputStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputStream) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (OutputStream) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x OutputStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputStream.Descriptor instead.
func (OutputStream) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type HostMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*HostMessage_ExecuteTask
	//	*HostMessage_CancelTask
	//	*HostMessage_Shutdown
	//	*HostMessage_Ping
	Payload       isHostMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostMessage) Reset() {
	*x = HostMessage{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMessage) ProtoMessage() {}

func (x *HostMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMessage.ProtoReflect.Descriptor instead.
func (*HostMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *HostMessage) GetPayload() isHostMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HostMessage) GetExecuteTask() *ExecuteTask {
	if x != nil {
		if x, ok := x.Payload.(*HostMessage_ExecuteTask); ok {
			return x.ExecuteTask
		}
	}
	return nil
}

func (x *HostMessage) GetCancelTask() *CancelTask {
	if x != nil {
		if x, ok := x.Payload.(*HostMessage_CancelTask); ok {
			return x.CancelTask
		}
	}
	return nil
}

func (x *HostMessage) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Payload.(*HostMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *HostMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*HostMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isHostMessage_Payload interface {
	isHostMessage_Payload()
}

type HostMessage_ExecuteTask struct {
	ExecuteTask *ExecuteTask `protobuf:"bytes,1,opt,name=execute_task,json=executeTask,proto3,oneof"`
}

type HostMessage_CancelTask struct {
	CancelTask *CancelTask `protobuf:"bytes,2,opt,name=cancel_task,json=cancelTask,proto3,oneof"`
}

type HostMessage_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,3,opt,name=shutdown,proto3,oneof"`
}

type HostMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

func (*HostMessage_ExecuteTask) isHostMessage_Payload() {}

func (*HostMessage_CancelTask) isHostMessage_Payload() {}

func (*HostMessage_Shutdown) isHostMessage_Payload() {}

func (*HostMessage_Ping) isHostMessage_Payload() {}

// Execute code inside the VM
type ExecuteTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"` // python, javascript, go, rust, bash
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Stdin         string                 `protobuf:"bytes,4,opt,name=stdin,proto3" json:"stdin,omitempty"`
	TimeoutSecs   int32                  `protobuf:"varint,5,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"` // max execution time
	EnvVars       map[string]string      `protobuf:"bytes,6,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MemoryLimitMb int64                  `protobuf:"varint,7,opt,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"` // per-process memory limit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTask) Reset() {
	*x = ExecuteTask{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTask) ProtoMessage() {}

func (x *ExecuteTask) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTask.ProtoReflect.Descriptor instead.
func (*ExecuteTask) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteTask) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ExecuteTask) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteTask) GetStdin() string {
	if x != nil {
		return x.Stdin
	}
	return ""
}

func (x *ExecuteTask) GetTimeoutSecs() int32 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

func (x *ExecuteTask) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *ExecuteTask) GetMemoryLimitMb() int64 {
	if x != nil {
		return x.MemoryLimitMb
	}
	return 0
}

// Cancel a running task
type CancelTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTask) Reset() {
	*x = CancelTask{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTask) ProtoMessage() {}

func (x *CancelTask) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTask.ProtoReflect.Descriptor instead.
func (*CancelTask) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *CancelTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// Graceful shutdown
type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

// Health check
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Ping) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GuestMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GuestMessage_Ready
	//	*GuestMessage_TaskOutput
	//	*GuestMessage_TaskComplete
	//	*GuestMessage_Metrics
	//	*GuestMessage_Pong
	Payload       isGuestMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuestMessage) Reset() {
	*x = GuestMessage{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestMessage) ProtoMessage() {}

func (x *GuestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestMessage.ProtoReflect.Descriptor instead.
func (*GuestMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GuestMessage) GetPayload() isGuestMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GuestMessage) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Payload.(*GuestMessage_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *GuestMessage) GetTaskOutput() *TaskOutput {
	if x != nil {
		if x, ok := x.Payload.(*GuestMessage_TaskOutput); ok {
			return x.TaskOutput
		}
	}
	return nil
}

func (x *GuestMessage) GetTaskComplete() *TaskComplete {
	if x != nil {
		if x, ok := x.Payload.(*GuestMessage_TaskComplete); ok {
			return x.TaskComplete
		}
	}
	return nil
}

func (x *GuestMessage) GetMetrics() *Metrics {
	if x != nil {
		if x, ok := x.Payload.(*GuestMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *GuestMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*GuestMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isGuestMessage_Payload interface {
	isGuestMessage_Payload()
}

type GuestMessage_Ready struct {
	Ready *Ready `protobuf:"bytes,1,opt,name=ready,proto3,oneof"`
}

type GuestMessage_TaskOutput struct {
	TaskOutput *TaskOutput `protobuf:"bytes,2,opt,name=task_output,json=taskOutput,proto3,oneof"`
}

type GuestMessage_TaskComplete struct {
	TaskComplete *TaskComplete `protobuf:"bytes,3,opt,name=task_complete,json=taskComplete,proto3,oneof"`
}

type GuestMessage_Metrics struct {
	Metrics *Metrics `protobuf:"bytes,4,opt,name=metrics,proto3,oneof"`
}

type GuestMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,5,opt,name=pong,proto3,oneof"`
}

func (*GuestMessage_Ready) isGuestMessage_Payload() {}

func (*GuestMessage_TaskOutput) isGuestMessage_Payload() {}

func (*GuestMessage_TaskComplete) isGuestMessage_Payload() {}

func (*GuestMessage_Metrics) isGuestMessage_Payload() {}

func (*GuestMessage_Pong) isGuestMessage_Payload() {}

// Agent is ready to receive tasks
type Ready struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion       string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Hostname           string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	SupportedLanguages []string               `protobuf:"bytes,3,rep,name=supported_languages,json=supportedLanguages,proto3" json:"supported_languages,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Ready) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Ready) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Ready) GetSupportedLanguages() []string {
	if x != nil {
		return x.SupportedLanguages
	}
	return nil
}

// Streaming output from a running task
type TaskOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Stream        OutputStream           `protobuf:"varint,2,opt,name=stream,proto3,enum=sentiae.agent.v1.OutputStream" json:"stream,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOutput) Reset() {
	*x = TaskOutput{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutput) ProtoMessage() {}

func (x *TaskOutput) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutput.ProtoReflect.Descriptor instead.
func (*TaskOutput) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *TaskOutput) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskOutput) GetStream() OutputStream {
	if x != nil {
		return x.Stream
	}
	return OutputStream_STDOUT
}

func (x *TaskOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Task finished (success or failure)
type TaskComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // non-empty if internal agent error
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	CpuTimeMs     int64                  `protobuf:"varint,5,opt,name=cpu_time_ms,json=cpuTimeMs,proto3" json:"cpu_time_ms,omitempty"`
	MemoryPeakKb  int64                  `protobuf:"varint,6,opt,name=memory_peak_kb,json=memoryPeakKb,proto3" json:"memory_peak_kb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskComplete) Reset() {
	*x = TaskComplete{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskComplete) ProtoMessage() {}

func (x *TaskComplete) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskComplete.ProtoReflect.Descriptor instead.
func (*TaskComplete) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *TaskComplete) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskComplete) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskComplete) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskComplete) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TaskComplete) GetCpuTimeMs() int64 {
	if x != nil {
		return x.CpuTimeMs
	}
	return 0
}

func (x *TaskComplete) GetMemoryPeakKb() int64 {
	if x != nil {
		return x.MemoryPeakKb
	}
	return 0
}

// Resource usage metrics (sent periodically)
type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsedKb  int64                  `protobuf:"varint,3,opt,name=memory_used_kb,json=memoryUsedKb,proto3" json:"memory_used_kb,omitempty"`
	MemoryTotalKb int64                  `protobuf:"varint,4,opt,name=memory_total_kb,json=memoryTotalKb,proto3" json:"memory_total_kb,omitempty"`
	ActiveTasks   int32                  `protobuf:"varint,5,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	UptimeSecs    int64                  `protobuf:"varint,6,opt,name=uptime_secs,json=uptimeSecs,proto3" json:"uptime_secs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *Metrics) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Metrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Metrics) GetMemoryUsedKb() int64 {
	if x != nil {
		return x.MemoryUsedKb
	}
	return 0
}

func (x *Metrics) GetMemoryTotalKb() int64 {
	if x != nil {
		return x.MemoryTotalKb
	}
	return 0
}

func (x *Metrics) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *Metrics) GetUptimeSecs() int64 {
	if x != nil {
		return x.UptimeSecs
	}
	return 0
}

// Health check response
type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "healthy", "busy", "draining"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *Pong) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Pong) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x10sentiae.agent.v1\"\x85\x02\n" +
	"\vHostMessage\x12B\n" +
	"\fexecute_task\x18\x01 \x01(\v2\x1d.sentiae.agent.v1.ExecuteTaskH\x00R\vexecuteTask\x12?\n" +
	"\vcancel_task\x18\x02 \x01(\v2\x1c.sentiae.agent.v1.CancelTaskH\x00R\n" +
	"cancelTask\x128\n" +
	"\bshutdown\x18\x03 \x01(\v2\x1a.sentiae.agent.v1.ShutdownH\x00R\bshutdown\x12,\n" +
	"\x04ping\x18\x04 \x01(\v2\x16.sentiae.agent.v1.PingH\x00R\x04pingB\t\n" +
	"\apayload\"\xba\x02\n" +
	"\vExecuteTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x14\n" +
	"\x05stdin\x18\x04 \x01(\tR\x05stdin\x12!\n" +
	"\ftimeout_secs\x18\x05 \x01(\x05R\vtimeoutSecs\x12E\n" +
	"\benv_vars\x18\x06 \x03(\v2*.sentiae.agent.v1.ExecuteTask.EnvVarsEntryR\aenvVars\x12&\n" +
	"\x0fmemory_limit_mb\x18\a \x01(\x03R\rmemoryLimitMb\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"%\n" +
	"\n" +
	"CancelTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\n" +
	"\n" +
	"\bShutdown\"$\n" +
	"\x04Ping\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xb7\x02\n" +
	"\fGuestMessage\x12/\n" +
	"\x05ready\x18\x01 \x01(\v2\x17.sentiae.agent.v1.ReadyH\x00R\x05ready\x12?\n" +
	"\vtask_output\x18\x02 \x01(\v2\x1c.sentiae.agent.v1.TaskOutputH\x00R\n" +
	"taskOutput\x12E\n" +
	"\rtask_complete\x18\x03 \x01(\v2\x1e.sentiae.agent.v1.TaskCompleteH\x00R\ftaskComplete\x125\n" +
	"\ametrics\x18\x04 \x01(\v2\x19.sentiae.agent.v1.MetricsH\x00R\ametrics\x12,\n" +
	"\x04pong\x18\x05 \x01(\v2\x16.sentiae.agent.v1.PongH\x00R\x04pongB\t\n" +
	"\apayload\"y\n" +
	"\x05Ready\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12/\n" +
	"\x13supported_languages\x18\x03 \x03(\tR\x12supportedLanguages\"q\n" +
	"\n" +
	"TaskOutput\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x126\n" +
	"\x06stream\x18\x02 \x01(\x0e2\x1e.sentiae.agent.v1.OutputStreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xc1\x01\n" +
	"\fTaskComplete\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12\x1e\n" +
	"\vcpu_time_ms\x18\x05 \x01(\x03R\tcpuTimeMs\x12$\n" +
	"\x0ememory_peak_kb\x18\x06 \x01(\x03R\fmemoryPeakKb\"\xda\x01\n" +
	"\aMetrics\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12$\n" +
	"\x0ememory_used_kb\x18\x03 \x01(\x03R\fmemoryUsedKb\x12&\n" +
	"\x0fmemory_total_kb\x18\x04 \x01(\x03R\rmemoryTotalKb\x12!\n" +
	"\factive_tasks\x18\x05 \x01(\x05R\vactiveTasks\x12\x1f\n" +
	"\vuptime_secs\x18\x06 \x01(\x03R\n" +
	"uptimeSecs\"<\n" +
	"\x04Pong\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status*&\n" +
	"\fOutputStream\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01b\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_agent_proto_goTypes = []any{
	(OutputStream)(0),    // 0: sentiae.agent.v1.OutputStream
	(*HostMessage)(nil),  // 1: sentiae.agent.v1.HostMessage
	(*ExecuteTask)(nil),  // 2: sentiae.agent.v1.ExecuteTask
	(*CancelTask)(nil),   // 3: sentiae.agent.v1.CancelTask
	(*Shutdown)(nil),     // 4: sentiae.agent.v1.Shutdown
	(*Ping)(nil),         // 5: sentiae.agent.v1.Ping
	(*GuestMessage)(nil), // 6: sentiae.agent.v1.GuestMessage
	(*Ready)(nil),        // 7: sentiae.agent.v1.Ready
	(*TaskOutput)(nil),   // 8: sentiae.agent.v1.TaskOutput
	(*TaskComplete)(nil), // 9: sentiae.agent.v1.TaskComplete
	(*Metrics)(nil),      // 10: sentiae.agent.v1.Metrics
	(*Pong)(nil),         // 11: sentiae.agent.v1.Pong
	nil,                  // 12: sentiae.agent.v1.ExecuteTask.EnvVarsEntry
}
var file_agent_proto_depIdxs = []int32{
	2,  // 0: sentiae.agent.v1.HostMessage.execute_task:type_name -> sentiae.agent.v1.ExecuteTask
	3,  // 1: sentiae.agent.v1.HostMessage.cancel_task:type_name -> sentiae.agent.v1.CancelTask
	4,  // 2: sentiae.agent.v1.HostMessage.shutdown:type_name -> sentiae.agent.v1.Shutdown
	5,  // 3: sentiae.agent.v1.HostMessage.ping:type_name -> sentiae.agent.v1.Ping
	12, // 4: sentiae.agent.v1.ExecuteTask.env_vars:type_name -> sentiae.agent.v1.ExecuteTask.EnvVarsEntry
	7,  // 5: sentiae.agent.v1.GuestMessage.ready:type_name -> sentiae.agent.v1.Ready
	8,  // 6: sentiae.agent.v1.GuestMessage.task_output:type_name -> sentiae.agent.v1.TaskOutput
	9,  // 7: sentiae.agent.v1.GuestMessage.task_complete:type_name -> sentiae.agent.v1.TaskComplete
	10, // 8: sentiae.agent.v1.GuestMessage.metrics:type_name -> sentiae.agent.v1.Metrics
	11, // 9: sentiae.agent.v1.GuestMessage.pong:type_name -> sentiae.agent.v1.Pong
	0,  // 10: sentiae.agent.v1.TaskOutput.stream:type_name -> sentiae.agent.v1.OutputStream
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*HostMessage_ExecuteTask)(nil),
		(*HostMessage_CancelTask)(nil),
		(*HostMessage_Shutdown)(nil),
		(*HostMessage_Ping)(nil),
	}
	file_agent_proto_msgTypes[5].OneofWrappers = []any{
		(*GuestMessage_Ready)(nil),
		(*GuestMessage_TaskOutput)(nil),
		(*GuestMessage_TaskComplete)(nil),
		(*GuestMessage_Metrics)(nil),
		(*GuestMessage_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
